-- =====================================================================
-- Gestão de SLA — tabela base do banco compartilhado (Supabase)
-- =====================================================================
-- Idempotente: pode ser executado de novo sem apagar dados.
-- Em um projeto NOVO rode este arquivo e depois supabase/migrations/002_auth_rls.sql.
-- Em um projeto que já está em uso, rode apenas a migração 002.
--
-- Cada registro do sistema (setor, fornecedor, avaliação, plano de ação) é uma linha:
--   collection = nome da coleção, id = id do registro, data = o objeto completo em JSON.
-- `seq` preserva a ordem de inserção usada pelo cache local do navegador.
-- As políticas de acesso (RLS) ficam na migração 002 — sem ela ninguém acessa a tabela.

create table if not exists public.sla_records (
  collection text        not null,
  id         text        not null,
  data       jsonb       not null,
  seq        bigint      generated by default as identity,
  updated_at timestamptz not null default now(),
  primary key (collection, id)
);

create index if not exists sla_records_seq_idx on public.sla_records (seq);

alter table public.sla_records enable row level security;

-- Tempo real: alterações de um gestor chegam na tela dos outros
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sla_records'
  ) then
    alter publication supabase_realtime add table public.sla_records;
  end if;
end $$;
