import { ActionPlan, Evaluation, Sector, Supplier, User } from '../types';

export const INITIAL_SECTORS: Sector[] = [
  {
    id: 'sec_eng_clinica',
    nome: 'Engenharia Clínica',
    gestorResponsavel: 'Ellen Manoela F Zerbetto',
    emailGestor: 'ellen.zerbetto@vilanovastar.com.br'
  },
  {
    id: 'sec_manutencao',
    nome: 'Manutenção',
    gestorResponsavel: 'Eduardo Gonçalves Dias',
    emailGestor: 'eduardo.gdias@vilanovastar.com.br'
  },
  {
    id: 'sec_medicina_nuclear',
    nome: 'Medicina Nuclear',
    gestorResponsavel: 'Karina G Moutinho C Vasconcelos',
    emailGestor: 'karina.moutinho@oncologiador.com.br'
  },
  {
    id: 'sec_sesmt',
    nome: 'SESMT',
    gestorResponsavel: 'Vivian Paula Da Cunha Silva',
    emailGestor: 'vivian.cunha@vilanovastar.com.br'
  },
  {
    id: 'sec_seguranca',
    nome: 'Segurança Patrimonial',
    gestorResponsavel: 'Alex Henrique Leite Dantes',
    emailGestor: 'alex.dantes@vilanovastar.com.br'
  },
  {
    id: 'sec_nutricao',
    nome: 'Nutrição',
    gestorResponsavel: 'Maira Oliveira Vanucci',
    emailGestor: 'maira.vanucci@vilanovastar.com.br'
  },
  {
    id: 'sec_governanca',
    nome: 'Governança',
    gestorResponsavel: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    emailGestor: 'jaqueline.monteiroc@vilanovastar.com.br'
  },
  {
    id: 'sec_laboratorio',
    nome: 'Laboratório',
    gestorResponsavel: 'Manoel Iomar De Medeiros',
    emailGestor: 'manoel.medeiros@vilanovastar.com.br'
  },
  {
    id: 'sec_rel_medico',
    nome: 'Relacionamento Médico',
    gestorResponsavel: 'Nicole Longo Fecarotta',
    emailGestor: 'nicole.longo@vilanovastar.com.br'
  },
  {
    id: 'sec_multi',
    nome: 'Equipe Multi',
    gestorResponsavel: 'Giseli Carvalho',
    emailGestor: 'giseli.carvalho@vilanovastar.com.br'
  },
  {
    id: 'sec_diretoria',
    nome: 'Diretoria Geral / Operacional',
    gestorResponsavel: 'Maria Luisa do Nascimento Moura',
    emailGestor: 'maria.nmoura@vilanovastar.com.br'
  }
];

export const INITIAL_USERS: User[] = [
  // Administrador Principal da Diretoria
  {
    id: 'usr_gabriel',
    nome: 'Gabriel Kotliarenko',
    email: 'gabriel.kotliarenko@vilanovastar.com.br',
    senha: '123',
    cargo: 'Diretoria Operacional (Admin)',
    role: 'DIRETORIA'
  },
  // Preposto Fornecedor Exemplo
  {
    id: 'usr_vo2_preposto',
    nome: 'Dr. André Fonseca',
    email: 'fornecedor@vo2care.com.br',
    senha: '123',
    cargo: 'Preposto / Diretor VO2 Care',
    role: 'FORNECEDOR',
    fornecedorId: 'sup_vo2'
  },

  // Gestores de Setores cadastrados
  {
    id: 'usr_maria_luisa',
    nome: 'Maria Luisa do Nascimento Moura',
    email: 'maria.nmoura@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Diretoria Geral',
    role: 'DIRETORIA',
    setorId: 'sec_diretoria'
  },
  {
    id: 'usr_daniel',
    nome: 'Daniel Favarão Del Negro',
    email: 'daniel.fnegro@saoluiz.com.br',
    senha: '123',
    cargo: 'Gestor - Diretoria Geral',
    role: 'DIRETORIA',
    setorId: 'sec_diretoria'
  },
  {
    id: 'usr_mariana',
    nome: 'Mariana Ferres Candiotto',
    email: 'mariana.candiotto@rededor.com.br',
    senha: '123',
    cargo: 'Gestor - Diretoria Geral',
    role: 'DIRETORIA',
    setorId: 'sec_diretoria'
  },
  {
    id: 'usr_ellen',
    nome: 'Ellen Manoela F Zerbetto',
    email: 'ellen.zerbetto@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Engenharia Clínica',
    role: 'GESTOR',
    setorId: 'sec_eng_clinica'
  },
  {
    id: 'usr_eduardo',
    nome: 'Eduardo Gonçalves Dias',
    email: 'eduardo.gdias@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Manutenção',
    role: 'GESTOR',
    setorId: 'sec_manutencao'
  },
  {
    id: 'usr_karina',
    nome: 'Karina G Moutinho C Vasconcelos',
    email: 'karina.moutinho@oncologiador.com.br',
    senha: '123',
    cargo: 'Gestor - Medicina Nuclear',
    role: 'GESTOR',
    setorId: 'sec_medicina_nuclear'
  },
  {
    id: 'usr_vivian',
    nome: 'Vivian Paula Da Cunha Silva',
    email: 'vivian.cunha@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - SESMT',
    role: 'GESTOR',
    setorId: 'sec_sesmt'
  },
  {
    id: 'usr_alex',
    nome: 'Alex Henrique Leite Dantes',
    email: 'alex.dantes@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Segurança Patrimonial',
    role: 'GESTOR',
    setorId: 'sec_seguranca'
  },
  {
    id: 'usr_maira',
    nome: 'Maira Oliveira Vanucci',
    email: 'maira.vanucci@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Nutrição',
    role: 'GESTOR',
    setorId: 'sec_nutricao'
  },
  {
    id: 'usr_jaqueline',
    nome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    email: 'jaqueline.monteiroc@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Governança',
    role: 'GESTOR',
    setorId: 'sec_governanca'
  },
  {
    id: 'usr_manoel',
    nome: 'Manoel Iomar De Medeiros',
    email: 'manoel.medeiros@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Laboratório',
    role: 'GESTOR',
    setorId: 'sec_laboratorio'
  },
  {
    id: 'usr_nicole',
    nome: 'Nicole Longo Fecarotta',
    email: 'nicole.longo@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Relacionamento Médico',
    role: 'GESTOR',
    setorId: 'sec_rel_medico'
  },
  {
    id: 'usr_giseli',
    nome: 'Giseli Carvalho',
    email: 'giseli.carvalho@vilanovastar.com.br',
    senha: '123',
    cargo: 'Gestor - Equipe Multi',
    role: 'GESTOR',
    setorId: 'sec_multi'
  }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  // Manutenção
  {
    id: 'sup_acquasuly',
    cnpj: '43.139.722/0001-34',
    razaoSocial: 'Acquasuly Engenharia Em Agua Quente E Gas LTDA',
    nomeFantasia: 'Acquasuly Engenharia',
    categoriaServico: 'Manutenção nos Aquecedores e Boilers',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS24-016-00',
    vigenciaFim: '2027-01-08'
  },
  {
    id: 'sup_air_liquide_manut',
    cnpj: '00.331.788/0001-19',
    razaoSocial: 'Air Liquide Brasil LTDA',
    nomeFantasia: 'Air Liquide (Manutenção)',
    categoriaServico: 'Gases Medicinais - Manutenção',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: '0',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_argus',
    cnpj: '12.096.667/0001-19',
    razaoSocial: 'Argus Produtos E Sistemas Contra Incêndio Ltda',
    nomeFantasia: 'Argus Contra Incêndio',
    categoriaServico: 'Manutenção do sistema de combate a incêndio',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede24-409-00',
    vigenciaFim: '2028-01-02'
  },
  {
    id: 'sup_ccl',
    cnpj: '00.236.854/0001-71',
    razaoSocial: 'CCL Manutenção de Capelas',
    nomeFantasia: 'CCL Capelas',
    categoriaServico: 'Manutenção Capelas de Exaustão',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS20-037-00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_controlbio',
    cnpj: '67.185.108/0001-77',
    razaoSocial: 'Controlbio assessoria Técnica Microbiológica SS LTDA',
    nomeFantasia: 'Controlbio Microbiologia',
    categoriaServico: 'Análise Microbiológica de Ambientes',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS/21-027/00',
    vigenciaFim: '2026-02-28'
  },
  {
    id: 'sup_controller',
    cnpj: '07.230.898/0001-33',
    razaoSocial: 'Controller Smart Automação LTDA',
    nomeFantasia: 'Controller Smart',
    categoriaServico: 'Automação Predial Hospitalar',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS20-043-03',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_daikin',
    cnpj: '02.172.568/0006-20',
    razaoSocial: 'Daikin Ar Condicionado Brasil LTDA',
    nomeFantasia: 'Daikin Chillers',
    categoriaServico: 'Manutenção de Chiller e Climatização',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'oncostar-19-060-02',
    vigenciaFim: '2026-11-13'
  },
  {
    id: 'sup_schindler',
    cnpj: '00.028.986/0051-77',
    razaoSocial: 'Elevadores Atlas Schindler LTDA',
    nomeFantasia: 'Atlas Schindler',
    categoriaServico: 'Manutenção de Elevadores e Escadas Rolantes',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-SCHINDLER-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_engepower',
    cnpj: '00.772.864/0001-21',
    razaoSocial: 'Engepower Eng e Com LTDA',
    nomeFantasia: 'Engepower Subestações',
    categoriaServico: 'Manutenção Preventiva e Corretiva de Subestação',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede/18-102/01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_everest',
    cnpj: '01.953.146/0001-14',
    razaoSocial: 'Everest Comércio de Refrigeração e Serviços SLU LTDA',
    nomeFantasia: 'Everest Purificadores',
    categoriaServico: 'Higienização externa dos purificadores',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-EVEREST-01',
    vigenciaFim: '2027-05-14'
  },
  {
    id: 'sup_kpm',
    cnpj: '18.126.361/0001-44',
    razaoSocial: 'KPM SERVICE LTDA',
    nomeFantasia: 'KPM Climatização PMOC',
    categoriaServico: 'Manutenção de Ar-condicionado - PMOC',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede25-227-00',
    vigenciaFim: '2031-05-06'
  },
  {
    id: 'sup_manusa',
    cnpj: '14.995.623/0001-56',
    razaoSocial: 'Manusa Do Brasil Industria E Com De Portas Automaticas Ltda',
    nomeFantasia: 'Manusa Portas Automáticas',
    categoriaServico: 'Automação das Portas Hospitalares',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS24-018-00',
    vigenciaFim: '2026-10-31'
  },
  {
    id: 'sup_microambiental',
    cnpj: '68.312.032/0001-66',
    razaoSocial: 'Microambiental Laboratório e Serviços em Água LTDA',
    nomeFantasia: 'Microambiental Águas',
    categoriaServico: 'Análise Potabilidade de Água Hospitalar',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-MICRO-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_nobreak',
    cnpj: '10.692.808/0001-30',
    razaoSocial: 'Nobreak Quality LTDA',
    nomeFantasia: 'Nobreak Quality',
    categoriaServico: 'Manutenção de Nobreak e Energia Crítica',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede-19-030-15',
    vigenciaFim: '2026-07-07'
  },
  {
    id: 'sup_petroserv',
    cnpj: '43.227.610/0001-35',
    razaoSocial: 'Petroserv Comércio de Derivados de Petróleo LTDA',
    nomeFantasia: 'Petroserv Diesel',
    categoriaServico: 'Circulação e Fornecimento de Diesel para Geradores',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede/18-089/05',
    vigenciaFim: '2027-10-02'
  },
  {
    id: 'sup_rdi',
    cnpj: '52.133.485/0001-95',
    razaoSocial: 'RDI Bender LTDA',
    nomeFantasia: 'RDI Bender IT Médico',
    categoriaServico: 'Manutenção do Sistema IT Médico',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS24-011-00',
    vigenciaFim: '2027-08-11'
  },
  {
    id: 'sup_sos_portas',
    cnpj: '05.357.829/0001-60',
    razaoSocial: 'SOS Portas Corta Fogo LTDA',
    nomeFantasia: 'SOS Portas Corta Fogo',
    categoriaServico: 'Manutenção em Portas Corta Fogo',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS25-150-00',
    vigenciaFim: '2026-10-02'
  },
  {
    id: 'sup_thyssen',
    cnpj: '90.347.840/0001-18',
    razaoSocial: 'ThyssenKrupp Elevadores LTDA',
    nomeFantasia: 'ThyssenKrupp TKE',
    categoriaServico: 'Manutenção Elevadores TKE',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-TKE-01',
    vigenciaFim: '2025-09-23'
  },
  {
    id: 'sup_wtc',
    cnpj: '19.524.939/0001-83',
    razaoSocial: 'W.T.C. Tecnologia em Tratamento de Água LTDA',
    nomeFantasia: 'WTC Água & Chiller',
    categoriaServico: 'Tratamento de Água / Chiller',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS20-071-00',
    vigenciaFim: '2026-06-27'
  },
  {
    id: 'sup_wgl',
    cnpj: '11.063.844/0001-06',
    razaoSocial: 'Wgl Solucoes Em Tecnologias E Servicos Ltda',
    nomeFantasia: 'WGL Geradores',
    categoriaServico: 'Manutenção nos Geradores de Energia',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede25-202-00',
    vigenciaFim: '2027-06-27'
  },
  {
    id: 'sup_aerocom',
    cnpj: '23.757.662/0001-06',
    razaoSocial: 'Wm Comercio E Servicos (Aerocom)',
    nomeFantasia: 'Aerocom Pneumático',
    categoriaServico: 'Manutenção do Sistema Correio Pneumático',
    setorResponsavelId: 'sec_manutencao',
    contatoNome: 'Eduardo Gonçalves Dias',
    contatoEmail: 'eduardo.gdias@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS21-025-01',
    vigenciaFim: 'Indeterminado'
  },

  // Engenharia Clínica
  {
    id: 'sup_air_liquide_eng',
    cnpj: '00.331.788/0023-24',
    razaoSocial: 'Air Liquide Brasil LTDA',
    nomeFantasia: 'Air Liquide Gases Medicinais',
    categoriaServico: 'Gases Medicinais - Engenharia Clínica',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-AIRLIQUIDE-ENG',
    vigenciaFim: '2027-08-10'
  },
  {
    id: 'sup_baxter',
    cnpj: '49.351.789/0002-61',
    razaoSocial: 'Baxter Hospitalar LTDA',
    nomeFantasia: 'Baxter Starling',
    categoriaServico: 'Locação de monitor de débito cardíaco (Starling)',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-BAXTER-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_bbraun',
    cnpj: '31.673.254/0001-02',
    razaoSocial: 'Bbraun Laboratórios S/A',
    nomeFantasia: 'BBraun Bombas Infusão',
    categoriaServico: 'Locação de bombas de infusão (Perfusor/Infusomat Space)',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Oncostar-19-054-00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_brainlab',
    cnpj: '02.981.566/0001-77',
    razaoSocial: 'Brainlab LTDA',
    nomeFantasia: 'Brainlab Neuronavegador',
    categoriaServico: 'Manutenção de Neuronavegador Cirúrgico',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede23-310-01',
    vigenciaFim: '2026-04-16'
  },
  {
    id: 'sup_brazil3',
    cnpj: '10.515.403/0001-27',
    razaoSocial: 'Brazil 3 Business LTDA',
    nomeFantasia: 'Brazil 3 Hologic Mamografia',
    categoriaServico: 'Manutenção de equipamento de Mamografia (Hologic)',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'REDE/21-275/00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_canon',
    cnpj: '46.563.938/0001-10',
    razaoSocial: 'Canon Medical Systems do Brasil LTDA',
    nomeFantasia: 'Canon Medical Ultrassom',
    categoriaServico: 'Manutenção de Ultrassom / bens móveis',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede19-037-25',
    vigenciaFim: '2026-02-01'
  },
  {
    id: 'sup_carestream',
    cnpj: '08.546.929/0003-94',
    razaoSocial: 'Carestream Health Brasil Comércio e Serviços LTDA',
    nomeFantasia: 'Carestream Raio-X & Dry',
    categoriaServico: 'Manutenção de impressora/revelador a seco (Dry) e Raio-X',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-CARESTREAM-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_cisa',
    cnpj: '05.120.289/0001-04',
    razaoSocial: 'Cisa Brasile LTDA',
    nomeFantasia: 'Cisa Termodesinfectora',
    categoriaServico: 'Manutenção de equipamento Termodesinfectora CME',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-CISA-01',
    vigenciaFim: '2025-09-30'
  },
  {
    id: 'sup_drager',
    cnpj: '61.185.922/0001-05',
    razaoSocial: 'Drager do Brasil LTDA',
    nomeFantasia: 'Drager Anestesia',
    categoriaServico: 'Manutenção de equipamentos de Anestesia',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-DRAGER-01',
    vigenciaFim: '2025-09-30'
  },
  {
    id: 'sup_ge_healthcare',
    cnpj: '00.029.372/0003-02',
    razaoSocial: 'GE Healthcare do Brasil LTDA',
    nomeFantasia: 'GE Healthcare Imagem',
    categoriaServico: 'Manutenção de equipamentos de imagem (Ressonância/Tomografia)',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede16-077-28',
    vigenciaFim: '2029-08-30'
  },
  {
    id: 'sup_strattner',
    cnpj: '33.250.713/0001-62',
    razaoSocial: 'H Strattner e Cia LTDA',
    nomeFantasia: 'Strattner CyberKnife',
    categoriaServico: 'Manutenção de sistema robótico (CyberKnife)',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS20-051-00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_invita',
    cnpj: '22.149.853/0001-22',
    razaoSocial: 'Invita Serviços de Manutenção LTDA',
    nomeFantasia: 'Invita TomoTherapy',
    categoriaServico: 'Manutenção e reparação preventiva (CyberKnife e TomoTherapy)',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'OncoStar23-005-00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_steris',
    cnpj: '59.233.783/0004-49',
    razaoSocial: 'Steris Solutions do Brasil Importação e Comercialização',
    nomeFantasia: 'Steris Lavadoras CME',
    categoriaServico: 'Manutenção de Lavadoras e Esterilizadoras CME',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede22-338-03',
    vigenciaFim: '2026-04-23'
  },
  {
    id: 'sup_techmed',
    cnpj: '55.444.333/0001-22',
    razaoSocial: 'TechMed Engenharia Clínica & Equipamentos',
    nomeFantasia: 'TechMed Engenharia Clínica',
    categoriaServico: 'Manutenção Preventiva/Corretiva e Calibração de Equipamentos Médicos',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-2023/078',
    vigenciaFim: '2027-08-31'
  },
  {
    id: 'sup_varian',
    cnpj: '03.009.915/0001-56',
    razaoSocial: 'Varian Medical Systems Brasil LTDA',
    nomeFantasia: 'Varian TrueBeam Radioterapia',
    categoriaServico: 'Manutenção de equipamentos de radioterapia (Gating/TrueBeam)',
    setorResponsavelId: 'sec_eng_clinica',
    contatoNome: 'Ellen Manoela F Zerbetto',
    contatoEmail: 'ellen.zerbetto@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede17-122-07',
    vigenciaFim: '2025-12-30'
  },

  // Governança / Hotelaria
  {
    id: 'sup_allpark',
    cnpj: '60.537.263/0001-66',
    razaoSocial: 'ALLPARK EMPREENDIMENTOS, PARTICIPAÇÕES E SERVIÇOS S/A',
    nomeFantasia: 'Estapar Allpark Estacionamento',
    categoriaServico: 'Mão de obra e serviços de Estacionamento Valet',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS-19-008-00',
    vigenciaFim: '2028-05-01'
  },
  {
    id: 'sup_bobson',
    cnpj: '02.815.733/0001-00',
    razaoSocial: 'BOBSON SÃO PAULO HIGIENE LTDA',
    nomeFantasia: 'Bobson Odorizadores WCs',
    categoriaServico: 'Locação de Odorizadores WCs',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede-21-075-19',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_cleaning_sol',
    cnpj: '15.808.202/0001-99',
    razaoSocial: 'Cleaning Solutions LTDA',
    nomeFantasia: 'Cleaning Solutions Pisos',
    categoriaServico: 'Manutenção e tratamento de piso hospitalar',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-CLEANING-01',
    vigenciaFim: '2028-08-15'
  },
  {
    id: 'sup_radio_ibiza',
    cnpj: '06.984.948/0001-05',
    razaoSocial: 'GASPARIAN E SALAMÃO (Radio Ibiza)',
    nomeFantasia: 'Radio Ibiza Ambientação',
    categoriaServico: 'Serviços especializados de Licenciamento de estação de rádio',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS-23-031-00',
    vigenciaFim: '2025-01-02'
  },
  {
    id: 'sup_hpx_lavanderia',
    cnpj: '12.942.098/0001-85',
    razaoSocial: 'HPX HIGIENIZAÇÃO TEXTIL LTDA',
    nomeFantasia: 'HPX Lavanderia Hospitalar',
    categoriaServico: 'Serviços de Lavanderia Hospitalar',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS-21-049-00',
    vigenciaFim: '2024-11-01'
  },
  {
    id: 'sup_portinari',
    cnpj: '09.032.026/0001-09',
    razaoSocial: 'LAVANDERIA PORTINARI LTDA',
    nomeFantasia: 'Lavanderia Portinari',
    categoriaServico: 'Serviços de Lavanderia Enxoval',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-PORTINARI-01',
    vigenciaFim: '2027-03-09'
  },
  {
    id: 'sup_maria_marcia',
    cnpj: '42.479.371/0001-48',
    razaoSocial: 'MARIA MARCIA CONVENIENCE PRESENTES',
    nomeFantasia: 'Maria Marcia Loja Conveniência',
    categoriaServico: 'Locação de espaço para loja de conveniência/presentes',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS-23-019-01',
    vigenciaFim: '2025-07-28'
  },
  {
    id: 'sup_multilixo',
    cnpj: '01.382.443/0001-57',
    razaoSocial: 'MULTILIXO REMOÇÕES DE LIXO S/S LTDA/FLACIPEL',
    nomeFantasia: 'Multilixo Coleta de Resíduos',
    categoriaServico: 'Remoção e coleta de resíduos (lixo hospitalar e reciclável)',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS-22-047-01',
    vigenciaFim: '2028-04-17'
  },
  {
    id: 'sup_praxxis',
    cnpj: '05.424.004/0001-10',
    razaoSocial: 'PRAXXIS CONTROLE INTEGRADO DE PRAGAS LTDA',
    nomeFantasia: 'Praxxis Dedetização',
    categoriaServico: 'Controle Integrado de Pragas (dedetização/desinsetização)',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Oncostar-/19-030/00',
    vigenciaFim: '2021-03-29'
  },
  {
    id: 'sup_rb_facilities',
    cnpj: '52.951.890/0001-10',
    razaoSocial: 'RB FACILITIES SERVIÇOS LTDA',
    nomeFantasia: 'RB Facilities (Mão de Obra/Ascensoristas)',
    categoriaServico: 'Mão de Obra entrepostos, Ascensoristas e Bolsão Privativo',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VSN-23-059-00',
    vigenciaFim: '2026-12-31'
  },
  {
    id: 'sup_studio_d',
    cnpj: '12.115.152/0001-19',
    razaoSocial: 'STUDIO D ESSENCES COMERCIO E FABRICAÇÃO',
    nomeFantasia: 'Studio D Essências Aromatizantes',
    categoriaServico: 'Fornecimento/comercialização de essências aromatizantes',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS19-081-05',
    vigenciaFim: '2028-03-01'
  },
  {
    id: 'sup_top_service',
    cnpj: '00.973.749/0014-30',
    razaoSocial: 'Top Service Predial LTDA',
    nomeFantasia: 'Top Service Limpeza Predial',
    categoriaServico: 'Serviços de manutenção e limpeza predial hospitalar',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS-24-023-00',
    vigenciaFim: '2027-07-16'
  },
  {
    id: 'sup_vertas',
    cnpj: '68.112.747/0001-75',
    razaoSocial: 'VERTAS COMERCIO DE RESIDUOS TECNOLOGICOS LTDA',
    nomeFantasia: 'Vertas Lixo Eletrônico',
    categoriaServico: 'Comércio/gestão de resíduos tecnológicos (descarte eletrônico)',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Holding/19-111/02',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_voice_tech',
    cnpj: '68.112.747/0001-75',
    razaoSocial: 'VOICE TECHNOLOGY COMERCIO EXTERIOR LTDA',
    nomeFantasia: 'Voice Technology',
    categoriaServico: 'Serviços de Tecnologia de Voz e Comunicação',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS-23-064-00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_wesco',
    cnpj: '07.045.160/0001-04',
    razaoSocial: 'WESCO Gomes D\'Elia LTDA',
    nomeFantasia: 'Wesco Higiene',
    categoriaServico: 'Fornecimento/locação de equipamentos e produtos de higiene',
    setorResponsavelId: 'sec_governanca',
    contatoNome: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    contatoEmail: 'jaqueline.monteiroc@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-WESCO-01',
    vigenciaFim: '2025-10-02'
  },

  // Laboratório
  {
    id: 'sup_biomerieux',
    cnpj: '33.040.635/0006-86',
    razaoSocial: 'Biomérieux Brasil Indústria Ltda',
    nomeFantasia: 'Biomérieux Diagnósticos',
    categoriaServico: 'Comodato de equipamentos e licenciamento de software (REAL)',
    setorResponsavelId: 'sec_laboratorio',
    contatoNome: 'Manoel Iomar De Medeiros',
    contatoEmail: 'manoel.medeiros@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-BIOMERIEUX-01',
    vigenciaFim: '2026-12-08'
  },
  {
    id: 'sup_controllab',
    cnpj: '29.511.607/0001-18',
    razaoSocial: 'Controllab Controle de Qualidade para laboratórios Ltda',
    nomeFantasia: 'Controllab Qualidade',
    categoriaServico: 'Controle de Qualidade Laboratorial e Ensaios de Proficiência',
    setorResponsavelId: 'sec_laboratorio',
    contatoNome: 'Manoel Iomar De Medeiros',
    contatoEmail: 'manoel.medeiros@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-CONTROLLAB-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_eco_diag',
    cnpj: '23.011.000/0001-00',
    razaoSocial: 'Eco Diagnóstica Ltda',
    nomeFantasia: 'Eco Diagnóstica',
    categoriaServico: 'Fornecimento de kits/reagentes (F-line e Biomol M-10) comodato',
    setorResponsavelId: 'sec_laboratorio',
    contatoNome: 'Manoel Iomar De Medeiros',
    contatoEmail: 'manoel.medeiros@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'OncoStar23-011-00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_medlab',
    cnpj: '33.222.111/0001-55',
    razaoSocial: 'MedLab Análises Clínicas & Patologia S/S',
    nomeFantasia: 'MedLab Diagnósticos',
    categoriaServico: 'Exames Laboratoriais, Anatomia Patológica e Urgência',
    setorResponsavelId: 'sec_laboratorio',
    contatoNome: 'Manoel Iomar De Medeiros',
    contatoEmail: 'manoel.medeiros@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-2022/015',
    vigenciaFim: '2028-03-15'
  },
  {
    id: 'sup_ortho_clinical',
    cnpj: '21.921.393/0002-27',
    razaoSocial: 'Ortho Clinical Diagnostics LTDA',
    nomeFantasia: 'Ortho Clinical Equipamentos',
    categoriaServico: 'Locação de equipamentos de análises clínicas',
    setorResponsavelId: 'sec_laboratorio',
    contatoNome: 'Manoel Iomar De Medeiros',
    contatoEmail: 'manoel.medeiros@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-ORTHO-01',
    vigenciaFim: '2029-12-16'
  },
  {
    id: 'sup_sysmex',
    cnpj: '02.923.414/0001-18',
    razaoSocial: 'Sysmex do Brasil Industria e Comercio LTDA',
    nomeFantasia: 'Sysmex Diagnósticos',
    categoriaServico: 'Locação de equipamentos e reagentes de hematologia (Sysmex)',
    setorResponsavelId: 'sec_laboratorio',
    contatoNome: 'Manoel Iomar De Medeiros',
    contatoEmail: 'manoel.medeiros@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-SYSMEX-01',
    vigenciaFim: '2027-10-31'
  },
  {
    id: 'sup_vyttra',
    cnpj: '00.904.728/0012-09',
    razaoSocial: 'Vyttra Diagnósticos S.A',
    nomeFantasia: 'Vyttra Diagnósticos',
    categoriaServico: 'Locação e fornecimento de Kits de diagnóstico laboratorial',
    setorResponsavelId: 'sec_laboratorio',
    contatoNome: 'Manoel Iomar De Medeiros',
    contatoEmail: 'manoel.medeiros@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-VYTTRA-01',
    vigenciaFim: '2027-11-08'
  },
  {
    id: 'sup_werfen',
    cnpj: '02.004.662/0003-27',
    razaoSocial: 'Werfen Medical Ltda',
    nomeFantasia: 'Werfen Medical',
    categoriaServico: 'Fornecimento de reagentes e locação de equipamentos laboratoriais',
    setorResponsavelId: 'sec_laboratorio',
    contatoNome: 'Manoel Iomar De Medeiros',
    contatoEmail: 'manoel.medeiros@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-WERFEN-01',
    vigenciaFim: 'Indeterminado'
  },

  // Medicina Nuclear
  {
    id: 'sup_cyclobras',
    cnpj: '08.820.007/0001-61',
    razaoSocial: 'Cyclobras Indústria, Comercio e Serviços Laboratoriais LTDA',
    nomeFantasia: 'Cyclobras Radiofármacos',
    categoriaServico: 'Fornecimento de doses de FDG-F18 e PSMA-F18',
    setorResponsavelId: 'sec_medicina_nuclear',
    contatoNome: 'Karina G Moutinho C Vasconcelos',
    contatoEmail: 'karina.moutinho@oncologiador.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-CYCLOBRAS-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_eckert',
    cnpj: '21.423.605/0001-65',
    razaoSocial: 'Eckert & Ziegler Transporte de Radiofármacos',
    nomeFantasia: 'Eckert & Ziegler',
    categoriaServico: 'Transporte de radiofármacos sob demanda',
    setorResponsavelId: 'sec_medicina_nuclear',
    contatoNome: 'Karina G Moutinho C Vasconcelos',
    contatoEmail: 'karina.moutinho@oncologiador.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-ECKERT-01',
    vigenciaFim: 'Em Renovação'
  },
  {
    id: 'sup_ibf',
    cnpj: '14.864.868/0001-44',
    razaoSocial: 'IBF - Indústria Brasileira de Farmoquimicos',
    nomeFantasia: 'IBF Farmoquímicos',
    categoriaServico: 'Fornecimento do produto FDG-18F para diagnóstico PET/CT',
    setorResponsavelId: 'sec_medicina_nuclear',
    contatoNome: 'Karina G Moutinho C Vasconcelos',
    contatoEmail: 'karina.moutinho@oncologiador.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-IBF-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_ipen',
    cnpj: '00.402.552/0001-26',
    razaoSocial: 'IPEN Instituto de Pesquisas Energéticas e Nucleares',
    nomeFantasia: 'IPEN Radiofarmácia',
    categoriaServico: 'Fornecimento de Geradores e Radiofármacos Hospitalares',
    setorResponsavelId: 'sec_medicina_nuclear',
    contatoNome: 'Karina G Moutinho C Vasconcelos',
    contatoEmail: 'karina.moutinho@oncologiador.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-IPEN-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_rph',
    cnpj: '19.315.658/0001-10',
    razaoSocial: 'RPH Radiofarmacia Centralizada LTDA',
    nomeFantasia: 'RPH Radiofarmácia',
    categoriaServico: 'Manipulação de Doses de Radiofármacos',
    setorResponsavelId: 'sec_medicina_nuclear',
    contatoNome: 'Karina G Moutinho C Vasconcelos',
    contatoEmail: 'karina.moutinho@oncologiador.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS/19-047/00',
    vigenciaFim: 'Indeterminado'
  },

  // Nutrição
  {
    id: 'sup_melco',
    cnpj: '10.721.756/0001-83',
    razaoSocial: 'MELCO COMERCIO E INSTALACOES LTDA',
    nomeFantasia: 'Melco Cozinhas Industriais',
    categoriaServico: 'Manutenção em equipamentos de cozinha hospitalar',
    setorResponsavelId: 'sec_nutricao',
    contatoNome: 'Maira Oliveira Vanucci',
    contatoEmail: 'maira.vanucci@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS23-015-01',
    vigenciaFim: '2026-01-06'
  },
  {
    id: 'sup_nestle',
    cnpj: '60.409.075/0540-82',
    razaoSocial: 'Nestle Brasil Ltda',
    nomeFantasia: 'Nestlé Nespresso Professional',
    categoriaServico: 'Fornecimento de produtos e comodato de máquinas de café',
    setorResponsavelId: 'sec_nutricao',
    contatoNome: 'Maira Oliveira Vanucci',
    contatoEmail: 'maira.vanucci@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-NESTLE-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_prime_frio',
    cnpj: '30.482.421/0001-67',
    razaoSocial: 'Prime Frio Refrigeração LTDA',
    nomeFantasia: 'Prime Frio Refrigeração',
    categoriaServico: 'Manutenção preventiva e corretiva de refrigeração',
    setorResponsavelId: 'sec_nutricao',
    contatoNome: 'Maira Oliveira Vanucci',
    contatoEmail: 'maira.vanucci@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS22-011-00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_roland_villard',
    cnpj: '14.660.551/0001-96',
    razaoSocial: 'Roland Villard Servicos de Gastronomia LTDA',
    nomeFantasia: 'Roland Villard Gastronomia',
    categoriaServico: 'Consultoria em gastronomia hospitalar e arte culinária',
    setorResponsavelId: 'sec_nutricao',
    contatoNome: 'Maira Oliveira Vanucci',
    contatoEmail: 'maira.vanucci@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-ROLAND-01',
    vigenciaFim: '2027-11-27'
  },
  {
    id: 'sup_sisnacmed',
    cnpj: '10.444.624/0001-51',
    razaoSocial: 'SISNACMED Soluções em Saúde LTDA',
    nomeFantasia: 'SISNACMED Carros Burlodge',
    categoriaServico: 'Manutenção Preventiva nos carros de refeição (Burlodge)',
    setorResponsavelId: 'sec_nutricao',
    contatoNome: 'Maira Oliveira Vanucci',
    contatoEmail: 'maira.vanucci@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS25-005-00',
    vigenciaFim: '2027-01-23'
  },
  {
    id: 'sup_nutri',
    cnpj: '77.888.999/0001-44',
    razaoSocial: 'NutriCare Alimentação Hospitalar LTDA',
    nomeFantasia: 'NutriCare Alimentação',
    categoriaServico: 'Fornecimento de Refeições Pacientes, Acompanhantes e Refeitório',
    setorResponsavelId: 'sec_nutricao',
    contatoNome: 'Maira Oliveira Vanucci',
    contatoEmail: 'maira.vanucci@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-2024/110',
    vigenciaFim: '2026-10-31'
  },

  // Segurança Patrimonial
  {
    id: 'sup_dunamis',
    cnpj: '04.365.440/0001-01',
    razaoSocial: 'DUNAMIS SERVIÇOS EMPRESARIAIS TERCEIRIZADOS LTDA. ME',
    nomeFantasia: 'Dunamis Vigilância Patrimonial',
    categoriaServico: 'Vigilância Patrimonial e Segurança Armada/Desarmada',
    setorResponsavelId: 'sec_seguranca',
    contatoNome: 'Alex Henrique Leite Dantes',
    contatoEmail: 'alex.dantes@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'OncoStarFarm22-001-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_engeradios',
    cnpj: '45.656.883/0001-20',
    razaoSocial: 'Engeradios Rio Comércio de Telecomunicações LTDA',
    nomeFantasia: 'Engeradios Rádios',
    categoriaServico: 'Locação/manutenção de rádios de comunicação para segurança',
    setorResponsavelId: 'sec_seguranca',
    contatoNome: 'Alex Henrique Leite Dantes',
    contatoEmail: 'alex.dantes@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS19-103-03',
    vigenciaFim: '2026-02-01'
  },
  {
    id: 'sup_systempower',
    cnpj: '07.880.795/0001-19',
    razaoSocial: 'SYSTEMPOWER LTDA ME',
    nomeFantasia: 'Systempower CFTV',
    categoriaServico: 'Monitoramento e manutenção de Circuito Fechado de TV (CFTV)',
    setorResponsavelId: 'sec_seguranca',
    contatoNome: 'Alex Henrique Leite Dantes',
    contatoEmail: 'alex.dantes@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-SYSTEMPOWER-01',
    vigenciaFim: 'Indeterminado'
  },

  // SESMT
  {
    id: 'sup_fermar_fire',
    cnpj: '09.494.572/0001-49',
    razaoSocial: 'FERMAR FIRE PROJETOS DE SEGURANÇA CONTRA INCÊNDIO LTDA',
    nomeFantasia: 'Fermar Fire Segurança',
    categoriaServico: 'Projetos e Adequação de Segurança contra Incêndio',
    setorResponsavelId: 'sec_sesmt',
    contatoNome: 'Vivian Paula Da Cunha Silva',
    contatoEmail: 'vivian.cunha@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-FERMAR-01',
    vigenciaFim: '2028-05-01'
  },

  // Equipe Multi
  {
    id: 'sup_vo2',
    cnpj: '39.615.127/0001-50',
    razaoSocial: 'VO2 CARE Fisioterapia LTDA',
    nomeFantasia: 'VO2 Care Fisioterapia',
    categoriaServico: 'Prestação de serviços especializados de Fisioterapia',
    setorResponsavelId: 'sec_multi',
    contatoNome: 'Giseli Carvalho',
    contatoEmail: 'giseli.carvalho@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-2024/089',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_ceaf_fono',
    cnpj: '33.440.921/0001-24',
    razaoSocial: 'CEAF Fonoaudiologia LTDA',
    nomeFantasia: 'CEAF Fonoaudiologia',
    categoriaServico: 'Prestação de serviços especializados de Fonoaudiologia',
    setorResponsavelId: 'sec_multi',
    contatoNome: 'Giseli Carvalho',
    contatoEmail: 'giseli.carvalho@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-CEAF-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_psicologia_multi',
    cnpj: '22.685.201/0001-02',
    razaoSocial: 'Psicologia Especializada Hospitalar LTDA',
    nomeFantasia: 'Psicologia Hospitalar',
    categoriaServico: 'Prestação de serviços especializados de Psicologia',
    setorResponsavelId: 'sec_multi',
    contatoNome: 'Giseli Carvalho',
    contatoEmail: 'giseli.carvalho@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-PSICO-01',
    vigenciaFim: 'Indeterminado'
  },

  // Diretoria
  {
    id: 'sup_banco_sangue',
    cnpj: '10.808.204/0001-07',
    razaoSocial: 'Banco de sangue Hematologia e Hemoterapia LTDA',
    nomeFantasia: 'Banco de Sangue Hemoterapia',
    categoriaServico: 'Fornecimento de hemocomponentes e serviço de hematologia',
    setorResponsavelId: 'sec_diretoria',
    contatoNome: 'Maria Luisa do Nascimento Moura',
    contatoEmail: 'maria.nmoura@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-BANCOSANGUE-01',
    vigenciaFim: '2041-05-07'
  },
  {
    id: 'sup_cappen',
    cnpj: '08.746.768/0001-10',
    razaoSocial: 'Cappen Comunicação e Tecnologia LTDA',
    nomeFantasia: 'Cappen Web & Digital',
    categoriaServico: 'Criação e desenvolvimento de website',
    setorResponsavelId: 'sec_diretoria',
    contatoNome: 'Maria Luisa do Nascimento Moura',
    contatoEmail: 'maria.nmoura@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-CAPPEN-01',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_eritel',
    cnpj: '60.322.484/0001-17',
    razaoSocial: 'Eritel Telecomunicações LTDA',
    nomeFantasia: 'Eritel Telecomunicações',
    categoriaServico: 'Serviços de Infraestrutura de Telecomunicações',
    setorResponsavelId: 'sec_diretoria',
    contatoNome: 'Maria Luisa do Nascimento Moura',
    contatoEmail: 'maria.nmoura@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS21-035-01',
    vigenciaFim: '2026-04-22'
  },
  {
    id: 'sup_fresenius',
    cnpj: '56.094.410/0001-01',
    razaoSocial: 'Fresenius Medical Care Brasil LTDA',
    nomeFantasia: 'Fresenius Hemodiálise (TRS)',
    categoriaServico: 'Terapia Renal Substitutiva (TRS) / Hemodiálise sob demanda',
    setorResponsavelId: 'sec_diretoria',
    contatoNome: 'Maria Luisa do Nascimento Moura',
    contatoEmail: 'maria.nmoura@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'Rede20-092-00',
    vigenciaFim: 'Indeterminado'
  },
  {
    id: 'sup_nexxto',
    cnpj: '12.982.578/0001-70',
    razaoSocial: 'Nexxto Tecnologia LTDA',
    nomeFantasia: 'Nexxto Sensores Temperatura',
    categoriaServico: 'Sensores IoT de temperatura para farmácia e laboratório',
    setorResponsavelId: 'sec_diretoria',
    contatoNome: 'Maria Luisa do Nascimento Moura',
    contatoEmail: 'maria.nmoura@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'VNS22-036-03',
    vigenciaFim: '2026-03-20'
  },
  {
    id: 'sup_senne_liquor',
    cnpj: '54.529.250/0001-42',
    razaoSocial: 'Senne Liquor Diagnósticos LTDA',
    nomeFantasia: 'Senne Liquor Diagnósticos',
    categoriaServico: 'Análise especializada de Líquido Cefalorraquidiano (LCR)',
    setorResponsavelId: 'sec_diretoria',
    contatoNome: 'Maria Luisa do Nascimento Moura',
    contatoEmail: 'maria.nmoura@vilanovastar.com.br',
    contatoTelefone: '(11) 3000-0000',
    numeroContrato: 'CT-SENNE-01',
    vigenciaFim: 'Indeterminado'
  }
];

export const INITIAL_EVALUATIONS: Evaluation[] = [
  {
    id: 'eval_vo2_2026',
    fornecedorId: 'sup_vo2',
    setorId: 'sec_multi',
    ano: 2026,
    dataAvaliacao: '2026-06-15',
    gestorAvaliador: 'Giseli Carvalho',
    emailAvaliador: 'giseli.carvalho@vilanovastar.com.br',
    respostas: {
      leg_1: 5, leg_2: 5, leg_3: 4, leg_4: 4, leg_5: 5,
      comp_1: 5, comp_2: 4, comp_3: 5, comp_4: 5, comp_5: 4,
      qual_1: 5, qual_2: 4, qual_3: 4, qual_4: 'NA', qual_5: 5
    },
    observacoesLegais: 'Equipe altamente qualificada. Documentação dos fisioterapeutas 100% atualizada junto ao CREFITO.',
    observacoesComportamentais: 'Excelente relacionamento com o corpo clínico e equipe multiprofissional.',
    observacoesQualidade: 'Adesão total às diretrizes de desmame ventilatório da UTI.',
    parecerGeral: 'Fornecedor prestador de serviço de excelência no ciclo anual. Recomenda-se renovação contratual.',
    mediaLegais: 4.60,
    mediaComportamentais: 4.60,
    mediaQualidade: 4.50,
    mediaGeral: 4.60,
    statusMeta: 'DENTRO_DA_META',
    necessitaPlanoAcao: false,
    statusAssinatura: 'ASSINADO_CIENTE',
    dataCiencia: '2026-06-20',
    nomeSignatario: 'Dr. André Fonseca',
    cargoSignatario: 'Diretor de Operações VO2 Care',
    parecerFornecedor: 'Agradecemos o reconhecimento da equipe hospitalar no ciclo anual.'
  },
  {
    id: 'eval_tech_2026',
    fornecedorId: 'sup_techmed',
    setorId: 'sec_eng_clinica',
    ano: 2026,
    dataAvaliacao: '2026-06-12',
    gestorAvaliador: 'Ellen Manoela F Zerbetto',
    emailAvaliador: 'ellen.zerbetto@vilanovastar.com.br',
    respostas: {
      leg_1: 4, leg_2: 5, leg_3: 4, leg_4: 4, leg_5: 4,
      comp_1: 4, comp_2: 4, comp_3: 4, comp_4: 4, comp_5: 4,
      qual_1: 4, qual_2: 4, qual_3: 4, qual_4: 5, qual_5: 4
    },
    observacoesLegais: 'Cronograma anual de calibração em dia.',
    observacoesComportamentais: 'Equipe prestativa no atendimento a chamados.',
    observacoesQualidade: 'Ótima rastreabilidade de ordens de serviço.',
    parecerGeral: 'Cumpre satisfatoriamente os termos do contrato anual.',
    mediaLegais: 4.20,
    mediaComportamentais: 4.00,
    mediaQualidade: 4.40,
    mediaGeral: 4.20,
    statusMeta: 'DENTRO_DA_META',
    necessitaPlanoAcao: false,
    statusAssinatura: 'ASSINADO_CIENTE',
    dataCiencia: '2026-06-15',
    nomeSignatario: 'Eng. Bruno Silveira',
    cargoSignatario: 'Engenheiro Chefe TechMed'
  },
  {
    id: 'eval_clean_2026',
    fornecedorId: 'sup_clean',
    setorId: 'sec_governanca',
    ano: 2026,
    dataAvaliacao: '2026-06-18',
    gestorAvaliador: 'Jaqueline Cleide Aguiar Monteiro De Carvalho',
    emailAvaliador: 'jaqueline.monteiroc@vilanovastar.com.br',
    respostas: {
      leg_1: 4, leg_2: 4, leg_3: 3, leg_4: 2, leg_5: 3,
      comp_1: 4, comp_2: 3, comp_3: 3, comp_4: 4, comp_5: 3,
      qual_1: 4, qual_2: 3, qual_3: 3, qual_4: 'NA', qual_5: 3
    },
    observacoesLegais: 'Identificamos rotatividade de funcionários sem comunicação prévia.',
    observacoesComportamentais: 'Atrasos no atendimento a chamados de limpeza terminal de leitos.',
    observacoesQualidade: 'Necessidade de reforçar o treinamento do descarte correto de resíduos.',
    parecerGeral: 'Média Anual 3.40 ficou abaixo da meta mínima aceitável (4.00). Plano de ação em andamento.',
    mediaLegais: 3.20,
    mediaComportamentais: 3.40,
    mediaQualidade: 3.65,
    mediaGeral: 3.40,
    statusMeta: 'ABAIXO_DA_META',
    necessitaPlanoAcao: true,
    statusAssinatura: 'ENVIADO_FORNECEDOR'
  },
  {
    id: 'eval_medlab_2026',
    fornecedorId: 'sup_medlab',
    setorId: 'sec_laboratorio',
    ano: 2026,
    dataAvaliacao: '2026-06-10',
    gestorAvaliador: 'Manoel Iomar De Medeiros',
    emailAvaliador: 'manoel.medeiros@vilanovastar.com.br',
    respostas: {
      leg_1: 5, leg_2: 5, leg_3: 5, leg_4: 4, leg_5: 5,
      comp_1: 5, comp_2: 5, comp_3: 5, comp_4: 5, comp_5: 4,
      qual_1: 5, qual_2: 5, qual_3: 4, qual_4: 5, qual_5: 5
    },
    observacoesLegais: '100% de conformidade com normativas do PALC e ANVISA.',
    observacoesComportamentais: 'Atendimento impecável na liberação de exames de urgência da UTI.',
    observacoesQualidade: 'SLA de tempo de liberação de exames abaixo do limite contratual.',
    parecerGeral: 'Fornecedor referência de qualidade no hospital no ciclo anual.',
    mediaLegais: 4.80,
    mediaComportamentais: 4.80,
    mediaQualidade: 4.80,
    mediaGeral: 4.80,
    statusMeta: 'DENTRO_DA_META',
    necessitaPlanoAcao: false,
    statusAssinatura: 'ASSINADO_CIENTE',
    dataCiencia: '2026-06-14',
    nomeSignatario: 'Dra. Helena Martins',
    cargoSignatario: 'Diretora Técnica MedLab'
  },
  {
    id: 'eval_nutri_2026',
    fornecedorId: 'sup_nutri',
    setorId: 'sec_nutricao',
    ano: 2026,
    dataAvaliacao: '2026-06-25',
    gestorAvaliador: 'Maira Oliveira Vanucci',
    emailAvaliador: 'maira.vanucci@vilanovastar.com.br',
    respostas: {
      leg_1: 4, leg_2: 4, leg_3: 4, leg_4: 3, leg_5: 4,
      comp_1: 4, comp_2: 3, comp_3: 4, comp_4: 4, comp_5: 3,
      qual_1: 4, qual_2: 4, qual_3: 3, qual_4: 4, qual_5: 3
    },
    observacoesLegais: 'Documentação sanitária em ordem.',
    observacoesComportamentais: 'Ocorrências pontuais de temperatura nas refeições dos acompanhantes.',
    observacoesQualidade: 'Reclamações na pesquisa de satisfação dos pacientes internados.',
    parecerGeral: 'Média Anual 3.75 requer alinhamento e Plano de Ação para controle térmico do transporte.',
    mediaLegais: 3.80,
    mediaComportamentais: 3.60,
    mediaQualidade: 3.60,
    mediaGeral: 3.75,
    statusMeta: 'ABAIXO_DA_META',
    necessitaPlanoAcao: true,
    statusAssinatura: 'PENDENTE_ENVIO'
  }
];

export const INITIAL_ACTION_PLANS: ActionPlan[] = [
  {
    id: 'plan_clean_01',
    evaluationId: 'eval_clean_2026',
    fornecedorId: 'sup_clean',
    setorId: 'sec_governanca',
    ano: 2026,
    titulo: 'Readequação da Equipe de Governança e Foco em Leitos UTI',
    acao5W: 'Treinamento de reciclagem da equipe sobre higienização terminal e fixação de quadro de dimensionamento mínimo.',
    justificativa5W: 'Nota da avaliação anual foi 3.40 (Abaixo da Meta) devido a atrasos na liberação de leitos.',
    responsavel5W: 'Juliana Costa (CleanHospital) & Jaqueline Monteiro (Vila Nova Star)',
    prazo5W: '2026-07-30',
    onde5W: 'Setores de Internação e UTI Adulto',
    como5W: 'Auditorias semanais de higienização e implantação de check-list digital.',
    custo5W: 'Sem custo adicional ao contrato.',
    status: 'EM_ANDAMENTO',
    dataCriacao: '2026-06-19',
    observacoesAcompanhamento: 'Treinamento presencial agendado para o dia 05/07.'
  },
  {
    id: 'plan_nutri_01',
    evaluationId: 'eval_nutri_2026',
    fornecedorId: 'sup_nutri',
    setorId: 'sec_nutricao',
    ano: 2026,
    titulo: 'Adequação Térmica dos Carrinhos Isotérmicos de Refeições',
    acao5W: 'Aquisição e manutenção dos carros de transporte isotérmico de refeições dos pacientes.',
    justificativa5W: 'Avaliação Anual 3.75 devido a reclamações de refeições mornas.',
    responsavel5W: 'Ricardo Oliveira (NutriCare) & Maira Vanucci (Vila Nova Star)',
    prazo5W: '2026-08-10',
    onde5W: 'Cozinha Central e Enfeites de Copa',
    como5W: 'Troca das vedações dos carros térmicos e aferição de temperatura.',
    custo5W: 'R$ 4.200,00',
    status: 'EM_ANDAMENTO',
    dataCriacao: '2026-06-26'
  }
];
