-- =====================================================================
-- Migração 002 — Supabase Auth, perfis de acesso e RLS por perfil
-- =====================================================================
-- O que esta migração faz:
--   1. Cria public.profiles (perfil de acesso ligado a auth.users) e copia para ela
--      os usuários que hoje estão em sla_records (collection = 'users'), SEM a senha.
--   2. Apaga a coleção 'users' de sla_records (era onde ficavam as senhas em texto puro).
--   3. Remove a política "tudo liberado para anon" e cria políticas por perfil:
--        DIRETORIA  → lê e grava tudo; único perfil que gerencia usuários/fornecedores/setores
--        GESTOR     → lê e grava apenas registros do próprio setor
--        FORNECEDOR → lê apenas as próprias avaliações (e o cadastro/setor ligados a elas)
--                     e grava só a ciência/assinatura, pela função registrar_ciencia()
--        anon       → nenhum acesso
--   4. Vincula automaticamente o login (auth.users) ao perfil pelo e-mail.
--
-- Idempotente: pode ser executada de novo. Veja supabase/README.md para os passos no painel.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 0. Base (caso o projeto seja novo e schema.sql não tenha sido rodado)
-- ---------------------------------------------------------------------
create table if not exists public.sla_records (
  collection text        not null,
  id         text        not null,
  data       jsonb       not null,
  seq        bigint      generated by default as identity,
  updated_at timestamptz not null default now(),
  primary key (collection, id)
);
alter table public.sla_records enable row level security;
alter table public.sla_records add column if not exists updated_by uuid;

-- Funções auxiliares ficam fora do schema "public" para não virarem endpoints da API
create schema if not exists private;
grant usage on schema private to authenticated;

-- ---------------------------------------------------------------------
-- 1. Perfis de acesso
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id            text primary key,                  -- mesmo id usado pelo app (ex.: 'usr_gabriel')
  auth_user_id  uuid unique references auth.users (id) on delete set null,
  email         text not null,
  nome          text not null,
  cargo         text not null default '',
  role          text not null check (role in ('DIRETORIA', 'GESTOR', 'FORNECEDOR')),
  setor_id      text,                              -- obrigatório na prática para GESTOR
  fornecedor_id text,                              -- obrigatório na prática para FORNECEDOR
  updated_at    timestamptz not null default now()
);
create unique index if not exists profiles_email_key on public.profiles (lower(email));
alter table public.profiles enable row level security;

-- Copia os usuários atuais (sem o campo senha). Registros com e-mail repetido ou perfil
-- desconhecido são ignorados; confira o resultado com a consulta do README.
insert into public.profiles (id, email, nome, cargo, role, setor_id, fornecedor_id)
select r.id,
       lower(trim(r.data->>'email')),
       coalesce(nullif(trim(r.data->>'nome'), ''), lower(trim(r.data->>'email'))),
       coalesce(r.data->>'cargo', ''),
       r.data->>'role',
       nullif(r.data->>'setorId', ''),
       nullif(r.data->>'fornecedorId', '')
from public.sla_records r
where r.collection = 'users'
  and coalesce(trim(r.data->>'email'), '') <> ''
  and r.data->>'role' in ('DIRETORIA', 'GESTOR', 'FORNECEDOR')
order by r.seq
on conflict do nothing;

-- A partir daqui nenhuma senha fica guardada nos dados do sistema
delete from public.sla_records where collection = 'users';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'sla_records_collection_check') then
    alter table public.sla_records
      add constraint sla_records_collection_check
      check (collection in ('sectors', 'suppliers', 'evaluations', 'action_plans')) not valid;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- 2. Quem é o usuário da requisição (lido de profiles pelo auth.uid())
-- ---------------------------------------------------------------------
-- security definer: leem profiles sem depender das políticas da própria tabela.
create or replace function private.user_role() returns text
language sql stable security definer set search_path = ''
as $$ select p.role from public.profiles p where p.auth_user_id = auth.uid() $$;

create or replace function private.user_setor() returns text
language sql stable security definer set search_path = ''
as $$ select p.setor_id from public.profiles p where p.auth_user_id = auth.uid() $$;

create or replace function private.user_fornecedor() returns text
language sql stable security definer set search_path = ''
as $$ select p.fornecedor_id from public.profiles p where p.auth_user_id = auth.uid() $$;

-- Setores que o fornecedor precisa enxergar (nome do setor no laudo e na assinatura)
create or replace function private.fornecedor_setores() returns text[]
language sql stable security definer set search_path = ''
as $$
  select coalesce(array_agg(distinct s), '{}')
  from (
    select r.data->>'setorId' as s
    from public.sla_records r
    where r.collection = 'evaluations' and r.data->>'fornecedorId' = private.user_fornecedor()
    union
    select r.data->>'setorResponsavelId'
    from public.sla_records r
    where r.collection = 'suppliers' and r.id = private.user_fornecedor()
  ) x
  where s is not null
$$;

revoke all on function private.user_role(), private.user_setor(), private.user_fornecedor(),
  private.fornecedor_setores() from public, anon;
grant execute on function private.user_role(), private.user_setor(), private.user_fornecedor(),
  private.fornecedor_setores() to authenticated;

-- ---------------------------------------------------------------------
-- 3. Vínculo login ↔ perfil pelo e-mail
-- ---------------------------------------------------------------------
-- Quando um login é criado (convite do painel ou da tela de usuários), liga ao perfil.
create or replace function private.link_profile_to_new_auth_user() returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  update public.profiles
     set auth_user_id = new.id
   where auth_user_id is null
     and lower(email) = lower(new.email);
  return new;
end $$;

drop trigger if exists on_auth_user_created_link_profile on auth.users;
create trigger on_auth_user_created_link_profile
  after insert on auth.users
  for each row execute function private.link_profile_to_new_auth_user();

-- Quando a Diretoria cadastra um perfil (ou troca o e-mail), liga ao login que já existir.
create or replace function private.link_auth_user_to_profile() returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  new.email := lower(trim(new.email));
  if tg_op = 'INSERT' or new.email is distinct from old.email then
    select u.id into new.auth_user_id
      from auth.users u
     where lower(u.email) = new.email
     limit 1;
  end if;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists profiles_link_auth_user on public.profiles;
create trigger profiles_link_auth_user
  before insert or update on public.profiles
  for each row execute function private.link_auth_user_to_profile();

revoke all on function private.link_profile_to_new_auth_user(), private.link_auth_user_to_profile()
  from public, anon, authenticated;

-- Logins que já existiam antes desta migração
update public.profiles p
   set auth_user_id = u.id
  from auth.users u
 where p.auth_user_id is null
   and lower(u.email) = lower(p.email)
   and not exists (select 1 from public.profiles q where q.auth_user_id = u.id);

-- ---------------------------------------------------------------------
-- 4. Auditoria mínima: quem alterou cada registro por último
-- ---------------------------------------------------------------------
create or replace function private.stamp_record() returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end $$;

drop trigger if exists sla_records_stamp on public.sla_records;
create trigger sla_records_stamp
  before insert or update on public.sla_records
  for each row execute function private.stamp_record();
revoke all on function private.stamp_record() from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- 5. Permissões de tabela (anon não acessa nada)
-- ---------------------------------------------------------------------
revoke all on public.sla_records from anon;
revoke all on public.profiles from anon;

grant select, insert, update, delete on public.sla_records to authenticated;

-- auth_user_id só é definido pelos gatilhos acima, nunca pelo navegador
revoke all on public.profiles from authenticated;
grant select, delete on public.profiles to authenticated;
grant insert (id, email, nome, cargo, role, setor_id, fornecedor_id) on public.profiles to authenticated;
grant update (email, nome, cargo, role, setor_id, fornecedor_id) on public.profiles to authenticated;

-- ---------------------------------------------------------------------
-- 6. Políticas de sla_records
-- ---------------------------------------------------------------------
-- Remove todas as políticas antigas (inclusive a "using (true)" para anon)
do $$
declare
  pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'sla_records' loop
    execute format('drop policy %I on public.sla_records', pol.policyname);
  end loop;
end $$;

create policy sla_records_select on public.sla_records
  for select to authenticated
  using (
    case (select private.user_role())
      when 'DIRETORIA' then true
      when 'GESTOR' then
        case collection
          when 'sectors'      then id = (select private.user_setor())
          when 'suppliers'    then data->>'setorResponsavelId' = (select private.user_setor())
          when 'evaluations'  then data->>'setorId' = (select private.user_setor())
          when 'action_plans' then data->>'setorId' = (select private.user_setor())
          else false
        end
      when 'FORNECEDOR' then
        case collection
          when 'evaluations'  then data->>'fornecedorId' = (select private.user_fornecedor())
          when 'action_plans' then data->>'fornecedorId' = (select private.user_fornecedor())
          when 'suppliers'    then id = (select private.user_fornecedor())
          when 'sectors'      then id = any ((select private.fornecedor_setores())::text[])
          else false
        end
      else false
    end
  );

-- Escrita: Diretoria em tudo; Gestor só avaliações e planos de ação do próprio setor.
-- Fornecedor não grava direto na tabela (usa registrar_ciencia).
create policy sla_records_insert on public.sla_records
  for insert to authenticated
  with check (
    (select private.user_role()) = 'DIRETORIA'
    or (
      (select private.user_role()) = 'GESTOR'
      and collection in ('evaluations', 'action_plans')
      and data->>'setorId' = (select private.user_setor())
    )
  );

create policy sla_records_update on public.sla_records
  for update to authenticated
  using (
    (select private.user_role()) = 'DIRETORIA'
    or (
      (select private.user_role()) = 'GESTOR'
      and collection in ('evaluations', 'action_plans')
      and data->>'setorId' = (select private.user_setor())
    )
  )
  with check (
    (select private.user_role()) = 'DIRETORIA'
    or (
      (select private.user_role()) = 'GESTOR'
      and collection in ('evaluations', 'action_plans')
      and data->>'setorId' = (select private.user_setor())
    )
  );

create policy sla_records_delete on public.sla_records
  for delete to authenticated
  using (
    (select private.user_role()) = 'DIRETORIA'
    or (
      (select private.user_role()) = 'GESTOR'
      and collection in ('evaluations', 'action_plans')
      and data->>'setorId' = (select private.user_setor())
    )
  );

-- ---------------------------------------------------------------------
-- 7. Políticas de profiles
-- ---------------------------------------------------------------------
drop policy if exists profiles_select on public.profiles;
drop policy if exists profiles_insert on public.profiles;
drop policy if exists profiles_update on public.profiles;
drop policy if exists profiles_delete on public.profiles;

create policy profiles_select on public.profiles
  for select to authenticated
  using (auth_user_id = (select auth.uid()) or (select private.user_role()) = 'DIRETORIA');

create policy profiles_insert on public.profiles
  for insert to authenticated
  with check ((select private.user_role()) = 'DIRETORIA');

create policy profiles_update on public.profiles
  for update to authenticated
  using ((select private.user_role()) = 'DIRETORIA')
  with check ((select private.user_role()) = 'DIRETORIA');

create policy profiles_delete on public.profiles
  for delete to authenticated
  using ((select private.user_role()) = 'DIRETORIA');

-- ---------------------------------------------------------------------
-- 8. Ciência / assinatura do fornecedor
-- ---------------------------------------------------------------------
-- O fornecedor só altera estes campos, e só em avaliações do próprio fornecedorId.
-- Qualquer outro campo enviado é ignorado.
create or replace function public.registrar_ciencia(p_evaluation_id text, p_ciencia jsonb)
returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v_fornecedor text := private.user_fornecedor();
  v_patch jsonb;
  v_data jsonb;
begin
  if private.user_role() is distinct from 'FORNECEDOR' or v_fornecedor is null then
    raise exception 'Somente o fornecedor registra ciência por esta função.' using errcode = '42501';
  end if;

  select data into v_data
    from public.sla_records
   where collection = 'evaluations'
     and id = p_evaluation_id
     and data->>'fornecedorId' = v_fornecedor
     for update;
  if v_data is null then
    raise exception 'Avaliação não encontrada para este fornecedor.' using errcode = '42501';
  end if;

  select coalesce(jsonb_object_agg(key, value), '{}'::jsonb) into v_patch
    from jsonb_each(coalesce(p_ciencia, '{}'::jsonb))
   where key in ('statusAssinatura', 'dataCiencia', 'nomeSignatario', 'cargoSignatario',
                 'parecerFornecedor', 'assinaturaBase64', 'assinaturaDigitalUrl');

  -- O fornecedor só pode mudar o status para "ciente" ou "contestado"
  if v_patch->>'statusAssinatura' is distinct from v_data->>'statusAssinatura'
     and v_patch ? 'statusAssinatura'
     and v_patch->>'statusAssinatura' not in ('ASSINADO_CIENTE', 'CONTESTADO') then
    raise exception 'Status de assinatura inválido para o fornecedor.' using errcode = '42501';
  end if;

  update public.sla_records
     set data = data || v_patch
   where collection = 'evaluations'
     and id = p_evaluation_id
  returning data into v_data;

  return v_data;
end $$;

revoke all on function public.registrar_ciencia(text, jsonb) from public, anon;
grant execute on function public.registrar_ciencia(text, jsonb) to authenticated;

commit;
